<?php
/**
 * @file
 * Adds Angular to the site.
 */

/**
 * Implements hook_proprocess_page().
 *
 * Load Angular based on configuration settings.
 */
function grundsalg_angular_preprocess_page(&$variables) {
  $config = \Drupal::getContainer()->get('itk_angular.settings')->getAll();

  // Load the AngularJS.
  $variables['#attached']['library'][] = 'itk_angular/angular';

  // Defines the application tag that Angular will bootstrap.
  $variables['attributes']['data-ng-app'] = 'ITKAngular';
}

/**
 * Implements hook_js_alter().
 *
 * Add support for translations in angular templates searching for the
 * Drupal.t() functions in the HTML and JS code.
 */
function grundsalg_angular_js_alter(&$javascript, \Drupal\Core\Asset\AttachedAssetsInterface $assets) {
  $files = array();

  $path = 'modules/custom';

  // Files to scan for translations (js and templates).
  $extensions = Array( 'js', 'html' );

  // Find the files.
  $it = new RecursiveDirectoryIterator($path);
  foreach(new RecursiveIteratorIterator($it) as $file)  {
    $ext = pathinfo($file, PATHINFO_EXTENSION);
    if (in_array($ext, $extensions)) {
      $files[] = $file->getPathname();
    }
  }

  // Scan the files to get translations into the database.
  locale_js_translate($files);
}
