<?php
/**
 * @file
 * Add template for widget.
 */

/**
 * Implements hook_theme().
 */
function itk_floating_help_theme($existing, $type, $theme, $path) {
  return [
    'itk_floating_help_block' => [
      'template' => 'itk-floating-help-block',
      'variables' => [
        'floating_help_contact_label' => NULL,
        'floating_help_phone_label' => NULL,
        'floating_help_email_label' => NULL,
        'floating_help_button_label_closed' => NULL,
        'floating_help_button_label_open' => NULL,
        'floating_help_text' => NULL,
        'floating_help_contact' => NULL,
        'floating_help_phone' => NULL,
        'floating_help_email' => NULL],
    ],
  ];
}
