<?php
/**
 * @file
 * Contains hooks for itk_activity module.
 */

use Drupal\Component\Utility\Html;
use Drupal\image\Entity\ImageStyle;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implement hook_mail().
 */
function itk_activity_mail($key, &$message, $params) {
  $options = array(
    'langcode' => $message['language']->language,
  );

  switch ($key) {
    // Send a simple message from the contact form.
    case 'contact_owner':
      $message['subject'] = $params['subject'];
      $message['body'][] = t('@first_name @surname (@email, @phone) sent you a message about your activity: @node_title.', [
        '@first_name' => Html::escape($params['first_name']),
        '@surname' => Html::escape($params['surname']),
        '@email' => Html::escape($params['email']),
        '@phone' => Html::escape($params['phone']),
        '@node_title' => $params['node_title'],
      ], $options);

      $message['body'][] = Html::escape($params['message']);
      break;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * Node Activity preprocess.
 */
function itk_activity_preprocess_node__activity(&$variables) {
  $node = $variables['node'];

  // Get categories.
  $categories = [];
  foreach ($node->field_categories->referencedEntities() as $category) {
    $categories[] = $category->name->value;
  }

  $currentUser = \Drupal::currentUser();
  $currentPath = \Drupal::service('path.alias_manager')->getAliasByPath(\Drupal::service('path.current')->getPath());

  $signupButton = NULL;
  $externalSignupButton = NULL;

  // Only show register to logged in users.
  if (!$currentUser->isAnonymous()) {
    // Not anonymous user.
    $signedUpUsers = $node->field_signed_up_users->referencedEntities();

    $alreadyAdded = FALSE;

    // Is the user registered to the activity?
    foreach ($signedUpUsers as $user) {
      if ($user->uid->value == $currentUser->id()) {
        $alreadyAdded = TRUE;
        break;
      }
    }

    $signupButton = [
      'href' => \Drupal\Core\Url::fromRoute('itk_activity.action_signup', [
        'nid' => $node->id(),
        'destination' => $currentPath,
      ], ['absolute' => TRUE])->toString()
    ];

    if ($alreadyAdded) {
      $signupButton['title'] = t('Unregister');
    }
    else {
      $signupButton['title'] = t('Register');
    }

    $externalSignupButton = [
      'href' => \Drupal\Core\Url::fromRoute('itk_activity.external_signup_form', ['nid' => $node->id()])->toString(),
      'title' => t('Register other user'),
    ];
  } else {
    $signupButton = [
      'href' => '/user',
      'title' => t('Login to register'),
    ];
  }

  // Attach facebook share button js and drupalSettings.
  $variables['#attached']['library'][] = 'itk_activity/fb_share';
  $variables['#attached']['drupalSettings']['itk_activity'] = [
    'fbShare' => [
      'appId' => \Drupal::config('simple_fb_connect.settings')->get('app_id'),
      'apiVersion' => \Drupal::config('simple_fb_connect.settings')->get('api_version'),
      'url' => \Drupal\Core\Url::fromRoute('entity.node.canonical', ['node' => $node->id()], ['absolute' => TRUE])->toString(),
    ],
  ];

  // Urlencoded newlines.
  $newlines = rawurlencode("\n\n");

  // Setup mailto link.
  $mailtoParts = [
    "mailto:?subject=",
    rawurlencode(t('Here is a suggestion for an activity in a community in Aarhus')),
    "&body=",
    rawurlencode(t('Try to have a look at this activity in Aarhus.')),
    $newlines,
    rawurlencode($node->title->value),
    $newlines,
    rawurlencode(t('Open this link to see the activity')),
    ": ",
    \Drupal\Core\Url::fromRoute('entity.node.canonical', ['node' => $node->id()], ['absolute' => TRUE])->toString(),
  ];
  $mailto = implode("", $mailtoParts);

  // Add contact link button if user has permission to contact owner.
  $contactLink = NULL;
  if ($currentUser->hasPermission('contact itk_activity activity owner')) {
    $contactLink = [
      'title' => t('Contact owner'),
      'href' => \Drupal\Core\Url::fromRoute('itk_activity.action_contact', ['nid' => $node->id()])->toString(),
    ];
  }

  $numberOfParticipants = NULL;
  $signedUpUsers = NULL;

  // Show extra data if user is activity owner.
  if ($currentUser->id() == $node->uid->entity->id()) {
    // Add count of registered users.
    $numberOfParticipants = [
      'value' => $node->field_signed_up_users->count() + $node->field_external_signed_up_users->count(),
      'label' => t('Signed up users'),
    ];

    // Add list of signed up users.
    $signedUpUsers = [];

    foreach ($node->field_signed_up_users->referencedEntities() as $user) {
      $signedUpUsers[] = (object) [
        'username' => $user->name->value,
        'first_name' => $user->field_first_name->value,
        'surname' => $user->field_surname->value,
        'email' => $user->mail->value,
      ];
    }

    foreach ($node->field_external_signed_up_users->referencedEntities() as $user) {
      $signedUpUsers[] = (object) [
        'first_name' => $user->first_name->value,
        'surname' => $user->surname->value,
        'email' => $user->email->value,
      ];
    }
  }

  // Set data for template.
  $variables['activity'] = [
    'activityHero' => [
      'title' => $node->title->value,
      'image' => _itk_activity_get_image_url($node, 'activity'),
    ],
    'activityOverview' => [
      'headingWithIconDescription' => [
        'title' => t('Description'),
      ],
      'headingWithIconDetails' => [
        'title' => t('Details')
      ],
      'categories' => $categories,
      'info' => [
        'title' => t('Important information:'),
        'signup_required' => $node->field_signup_required->value ?
          t('Signup required') : NULL,
        'entry_requirements' => $node->field_entry_requirements->entity->name->value,
        'physical_requirements' => $node->field_physical_requirements->entity->name->value,
        'help_needed' => $node->field_help_needed->entity->name->value,
      ],
      'body' => check_markup($node->body->value, 'filtered_html'),
      'signedUpUsers' => [
        'users' => $signedUpUsers,
        'title' => t('Signed up users'),
        'labels' => [
          'username' => t('Username'),
          'first_name' => t('First name'),
          'surname' => t('Surname'),
          'mail' => t('Mail'),
        ],
      ],
      'meta' => [
        'date' => \Drupal::service('date.formatter')->format((new DateTime($node->field_date->value))->getTimestamp(), 'date_long'),
        'date_label' => t('Date'),
        'price' => _itk_activity_get_price_text($node->field_price->value),
        'price_label' => t('Price'),
        'start_time' => $node->field_time_start->value,
        'start_time_label' => t('Start time'),
        'end_time' => $node->field_time_end->value,
        'end_time_label' => t('End time'),
        'address' => $node->field_address->value,
        'address_label' => t('Address'),
        'owner' =>  $node->uid->entity->name->value,
        'owner_label' => t('Owner'),
        'numberOfParticipants' => $numberOfParticipants,
        'signupButton' => $signupButton,
        'signupExternalButton' => $externalSignupButton,
        'contactLink' => $contactLink,
        'socialShare' => [
          'buttons' => [
            [
              'title' => t('Share on facebook'),
              'jsClass' => 'js-facebook-share-button',
            ],
          ],
          'links' => [
            [
              'title' => t('Share by mail'),
              'href' => $mailto,
            ]
          ],
        ],
      ]
    ]
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * Node Activity Teaser preprocess.
 */
function itk_activity_preprocess_node__activity__teaser(&$variables) {
  $node = $variables['node'];

  $imageUrl = _itk_activity_get_image_url($node, 'activity_teaser');

  $variables['cardActivity'] = [
    'link' => $node->toUrl()->toString(),
    'cardHeader' => [
      'title' => $node->title->value,
      'image' => [
        'src' => $imageUrl,
      ],
    ],
    'cardInfo' => [
      'activityMetas' => [
        [
          'label' => t('Date'),
          'text' => \Drupal::service('date.formatter')->format((new DateTime($node->field_date->value))->getTimestamp(), 'date_medium'),
        ],
        [
          'label' => t('Area'),
          'text' => $node->field_area->value,
        ],
      ]
    ]
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * Node Activity Teaser Edit preprocess.
 *
 * Extends itk_activity_preprocess_node__activity__teaser() with
 *   two action buttons.
 */
function itk_activity_preprocess_node__activity__teaser_edit(&$variables) {
  // Extend teaser hook.
  itk_activity_preprocess_node__activity__teaser($variables);

  $node = $variables['node'];

  $variables['cardActivity']['cardActions'] = [
    'deleteButton' => [
      'title' => t('Delete'),
      'href' => \Drupal\Core\Url::fromRoute('entity.node.delete_form', ['node' => $node->id()], ['absolute' => TRUE])->toString(),
    ],
    'editButton' => [
      'title' => t('Edit'),
      'href' => \Drupal\Core\Url::fromRoute('entity.node.edit_form', ['node' => $node->id()], ['absolute' => TRUE])->toString(),
    ],
    'cloneButton' => [
      'title' => t('Clone'),
      'href' => \Drupal\Core\Url::fromRoute('itk_activity.action_clone', ['nid' => $node->id()], ['absolute' => TRUE])->toString(),
    ]
  ];
}

/**
 * Implements hook_field_widget_form_alter().
 */
function itk_activity_form_node_form_alter(&$form, &$form_state, &$form_id) {
  $form['body']['widget']['#after_build'][] = '_allowed_formats_remove_textarea_help';
}

/**
 * Get the text for the price.
 *
 * @param $price
 *   The value of the price field.
 * @return \Drupal\Core\StringTranslation\TranslatableMarkup
 *   The markup result.
 */
function _itk_activity_get_price_text($price) {
  // Set price text.
  if (!isset($price) || $price <= 0) {
    return t('Free');
  }
  else {
    return t(':price kr.', [':price' => $price]);
  }
}

/**
 * Get the image url for the activity.
 *
 * If activity does not have an image, try to get it from the selected
 * categories and finally fallback to a theme provided default image.
 *
 * @param $node
 *   The activity.
 * @param $imageStyle
 *   The image style to apply to the image.
 * @return \Drupal\Core\GeneratedUrl|null|string
 *   The url to the image.
 */
function _itk_activity_get_image_url($node, $imageStyle) {
  // Get image url.
  $imageUrl = NULL;
  if (isset($node->field_image->entity)) {
    $image = $node->field_image->entity->getFileUri();
    $imageUrl = ImageStyle::load($imageStyle)->buildUrl($image);
  }
  else {
    $referencedCategories = $node->field_categories->referencedEntities();

    // Search for category with default image. Select the first available.
    foreach ($referencedCategories as $category) {
      if (isset($category->field_default_image->entity)) {
        $image = $category->field_default_image->entity->getFileUri();
        $imageUrl = ImageStyle::load($imageStyle)->buildUrl($image);
        break;
      }
    }

    // If no image has been set, select placeholder image.
    if (!isset($imageUrl)) {
      // Load category default image url.
      $imageUrl = "/" . drupal_get_path('module', 'itk_activity') . "/images/activity_fallback.png";
    }
  }

  return $imageUrl;
}

/**
 * Hide all textarea help from a form element.
 *
 * @param $form_element
 * @param \FormStateInterface $form_state
 * @return mixed
 */
function _allowed_formats_remove_textarea_help($form_element, FormStateInterface $form_state) {

  if (isset($form_element[0]['format'])) {
    // All this stuff is needed to hide the help text.
    unset($form_element[0]['format']['guidelines']);
    unset($form_element[0]['format']['help']);
    unset($form_element[0]['format']['#type']);
    unset($form_element[0]['format']['#theme_wrappers']);
    $form_element[0]['format']['format']['#access'] = FALSE;
  }

  return $form_element;
}
