<?php
/**
 * @file
 * This module shows a message on cookies being used in the site.
 *
 * The EU Directive on Privacy and Electronic Communications.
 */

/**
 * Implements hook_theme().
 */
function itk_cookie_message_theme($existing, $type, $theme, $path) {
  return [
    'itk_cookie_message_block' => [
      'template' => 'itk-cookie-message-block',
      'variables' => ['variables' => NULL],
    ],
  ];
}

/**
 * Get settings for cookie messages.
 *
 * @param \Drupal\Core\Language\LanguageInterface $language
 *   The languge to use for translations.
 *
 * @return array
 *   The (localized) settings.
 */
function _itk_cookie_message_get_settings(\Drupal\Core\Language\LanguageInterface $language = NULL) {
  if ($language === NULL) {
    $language = \Drupal::languageManager()->getCurrentLanguage();
  }
  $config = \Drupal::config('itk_cookie_message.settings');
  $global_settings = $config->get();
  $localized_settings = $config->get($language->getId());

  if (!is_array($localized_settings)) {
    $localized_settings = array();
  }

  // Merge default values into global settings.
  $global_settings += array(
    'cookie_name' => 'accept_cookies',
    'cookie_lifetime' => 365 * 24 * 60 * 60,
    'template' => '',
  );

  // Merge default values into localized settings.
  $localized_settings += array(
    'text' => t('We use cookies to improve your user experience', array(), array('langcode' => $language->getId())),
    'read_more_url' => '/information-om-cookies',
    'read_more_text' => t('Read more about cookies', array(), array('langcode' => $language->getId())),
    'accept_button_text' => t('Accept cookies', array(), array('langcode' => $language->getId())),
  );

  return array_merge($global_settings, $localized_settings);
}
