<?php
/**
 * @file
 * This module shows a message on cookies being used in the site.
 *
 * The EU Directive on Privacy and Electronic Communications.
 */

/**
 * Implements hook_theme().
 */
function itk_cookie_message_theme($existing, $type, $theme, $path) {
  return [
    'itk_cookie_message_block' => [
      'template' => 'itk-cookie-message-block',
      'variables' => ['variables' => NULL],
    ],
  ];
}

/**
 * Get settings for cookie messages.
 *
 * @param \Drupal\Core\Language\LanguageInterface $language
 *   The language to use for translations. Defaults to current language.
 *
 * @return array
 *   The (localized) settings.
 */
function _itk_cookie_message_get_settings(\Drupal\Core\Language\LanguageInterface $language = NULL) {
  // Default language is current language.
  if (!isset($language)) {
    $language = \Drupal::languageManager()->getCurrentLanguage();
  }

  // Get config.
  $config = \Drupal::config('itk_cookie_message.settings');

  // Values that apply to all languages.
  $settings = [
    'cookie_name' => $config->get('cookie_name'),
    'cookie_lifetime' => $config->get('cookie_lifetime'),
  ];

  // Only configuration for given language.
  $localizedSettings = $config->get($language->getId());

  // If not set, use english config which is installed with the module.
  if (!isset($localizedSettings)) {
    $localizedSettings = $config->get('en');
  }

  return array_merge($settings, $localizedSettings);
}
