<?php
/**
 * @file
 * ITK info section module.
 */

/**
 * Implements hook_theme().
 */
function itk_info_section_theme($existing, $type, $theme, $path) {
  return [
    'itk_info_section_block' => [
      'template' => 'itk-info-section-block',
      'variables' => [
        'title' => NULL,
        'subtitle' => NULL,
        'question_1' => NULL,
        'answer_1' => NULL,
        'question_2' => NULL,
        'answer_2' => NULL,
        'question_3' => NULL,
        'answer_3' => NULL,
        'call_to_action_text' => NULL,
        'call_to_action_button_text' => NULL,
        'call_to_action_button_link' => NULL,
      ],
    ],
    'itk_info_section_block1' => [
      'template' => 'itk-info-section-block',
      'variables' => [
        'title' => NULL,
        'subtitle' => NULL,
        'question_1' => NULL,
        'answer_1' => NULL,
        'question_2' => NULL,
        'answer_2' => NULL,
        'question_3' => NULL,
        'answer_3' => NULL,
        'call_to_action_text' => NULL,
        'call_to_action_button_text' => NULL,
        'call_to_action_button_link' => NULL,
      ],
    ],
    'itk_info_section_block2' => [
      'template' => 'itk-info-section-block',
      'variables' => [
        'title' => NULL,
        'subtitle' => NULL,
        'question_1' => NULL,
        'answer_1' => NULL,
        'question_2' => NULL,
        'answer_2' => NULL,
        'question_3' => NULL,
        'answer_3' => NULL,
        'call_to_action_text' => NULL,
        'call_to_action_button_text' => NULL,
        'call_to_action_button_link' => NULL,
      ],
    ],
  ];
}
